# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ecological Forecasting @ UNR
email: rshriver@unr.edu
description: > # this means to ignore newlines until "baseurl:"
  Bob Shriver's course taught at UNR Spring 2022
url: "https://bobshriver.github.io/UNR-Ecoforecast" # the base hostname & protocol for your site
github_username:  bobshriver

# Build settings
markdown: kramdown

theme: jekyll-theme-minimal
